"""initial schema

Revision ID: a1404614fc25
Revises: 
Create Date: 2026-07-10 19:43:34.120078

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a1404614fc25'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('video_path', sa.String(length=1024), nullable=False),
    sa.Column('annotated_video_path', sa.String(length=1024), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('average_position_x', sa.Float(), nullable=False),
    sa.Column('average_position_y', sa.Float(), nullable=False),
    sa.Column('distance_covered_km', sa.Float(), nullable=False),
    sa.Column('heatmap', sa.JSON(), nullable=False),
    sa.Column('touches', sa.Integer(), nullable=False),
    sa.Column('passes_made', sa.Integer(), nullable=False),
    sa.Column('passes_received', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_match_id'), 'players', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_match_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
